// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD401j9IeYBUwmSiCm89nt3a2tHafiLjCA',
    appId: '1:145834658208:web:b4ad77d614861af6967cc5',
    messagingSenderId: '145834658208',
    projectId: 'shoppingapp-eee7c',
    authDomain: 'shoppingapp-eee7c.firebaseapp.com',
    storageBucket: 'shoppingapp-eee7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7AgW6ZaZjIYtV0PcYPTR0XE00jxsOURg',
    appId: '1:145834658208:android:94b9c6a21172ac1e967cc5',
    messagingSenderId: '145834658208',
    projectId: 'shoppingapp-eee7c',
    storageBucket: 'shoppingapp-eee7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc_yqE4RzEWOw5C1qAICTWCJn80nrrudQ',
    appId: '1:145834658208:ios:a4d997539e6070af967cc5',
    messagingSenderId: '145834658208',
    projectId: 'shoppingapp-eee7c',
    storageBucket: 'shoppingapp-eee7c.appspot.com',
    iosClientId: '145834658208-nla83mjjup21ajuqrsod20m951c1okul.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc_yqE4RzEWOw5C1qAICTWCJn80nrrudQ',
    appId: '1:145834658208:ios:a4d997539e6070af967cc5',
    messagingSenderId: '145834658208',
    projectId: 'shoppingapp-eee7c',
    storageBucket: 'shoppingapp-eee7c.appspot.com',
    iosClientId: '145834658208-nla83mjjup21ajuqrsod20m951c1okul.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearn',
  );
}
